In [26]:
import sys
import os
from pathlib import Path
sys.path.append(str(Path.cwd().parent).replace('\\', '/'))
from mlwpy import *
%matplotlib inline

In [29]:
row_vec = np.arange(5).reshape(1,5)
row_vec

array([[0, 1, 2, 3, 4]])

In [30]:
col_vec = np.arange(0,100,20).reshape(5,1)
col_vec

array([[ 0],
       [20],
       [40],
       [60],
       [80]])

In [33]:
print("row vec:", row_vec,
        "col_vec", col_vec,
        "dot:", np.dot(row_vec, col_vec), sep="\n")

row vec:
[[0 1 2 3 4]]
col_vec
[[ 0]
 [20]
 [40]
 [60]
 [80]]
dot:
[[600]]


In [34]:
np.dot(col_vec, row_vec)

array([[  0,   0,   0,   0,   0],
       [  0,  20,  40,  60,  80],
       [  0,  40,  80, 120, 160],
       [  0,  60, 120, 180, 240],
       [  0,  80, 160, 240, 320]])

In [40]:
oned_vec = np.arange(5)
print("oned_vec = ", oned_vec, "/ shpae = ", oned_vec.shape)  
print("row_vec = ", row_vec, "/ shpae = ", row_vec.shape)  


oned_vec =  [0 1 2 3 4] / shpae =  (5,)
row_vec =  [[0 1 2 3 4]] / shpae =  (1, 5)


In [53]:
D = np.array([[1,3],[2,5],[2,7],[3,2]])
print("D = ", D)
w = np.array([1.5, -3])
print("w = ", w)
print(np.dot(D,w))
try :
    np.dot(w,D)
except ValueError as e:
    print(e)

D =  [[1 3]
 [2 5]
 [2 7]
 [3 2]]
w =  [ 1.5 -3. ]
[ -7.5 -12.  -18.   -1.5]
shapes (2,) and (4,2) not aligned: 2 (dim 0) != 4 (dim 0)


In [55]:
def rdot(arr, brr):
    '인수를 반대로 넣는 np.dot'
    return np.dot(brr, arr)
rdot(w,D)

array([ -7.5, -12. , -18. ,  -1.5])